### ISSUE TITLE
Running behind basic HTTP auth proxy

### ISSUE THREAD

**Issue by whizz** [altangent/lnd-explorer#4]
Hello and thanks for your great work. I am trying to run this on my node, but I want some sort of authorization. So I put it behind an Apache proxy where I set the auth. It works on the standard requests, but apparently the AJAX requests to /api/... do not have the auth headers and thus are receiving 401. If I disable the auth, it works fine. 

I am not sure if it's even solvable with the current setup so I'd like to get some ideas how to handle the authorization. Anyone tried something like that? 

Here is the relevant part from my Apache conf:

```
ProxyPreserveHost On
ProxyPass "/" "http://localhost:8001/"
ProxyPassReverse "/" "http://localhost:8001/"

<Proxy *>
    AuthType Basic
    AuthName "LND explorer"
    AuthBasicProvider file
    AuthUserFile "/opt/lnd-explorer/passwords"
    Require valid-user
</Proxy>
...
```

**Comment by bmancini55** [comment]
Network connections are being made with the `fetch` API.  This functionality should be able to be supported by adding `credentials: 'same-origin'` option to the fetch calls.

On a side node, a bit of cleanup should be done to make that standardized across the app.  Right now, fetches are being directly invoked by container components, so the change would need to be made in a bunch of files.

**Comment by whizz** [comment]
Thanks for the pointer. I submitted PR for your consideration.
